### PR TITLE
Linux with: stronger parsing, LANG support; All: infer sizes when dev.size es null

### LINKED ISSUE #15: Linux: test fails when LANG is not english; parsing is weak on a new test case
I've found that parsing currently depends on specific english strings; i'm from Argentina (spanish).

For example, `npm run test` with `LANG=es_AR.utf8` makes test fail like this:

```
1) node-fs-filesystem
       linux integration tests
         native tests
           should properly parse the output of the filesystem command:
     TypeError: Cannot read property 'slice' of null
```

`null` is a failing `match` for the string `/Disk\s(.*):\s.*,\s(\d+)\sbytes,\s(\d+) sectors/` on src/linux/linux.js:116

On spanish **Disk** is **Disco**

### PR DESCRIPTION
**Pull request by jacargentina**
See #15 for details

### CODE REVIEW

**Comment by jacargentina** [comment]
@philippefutureboy the only "failing" here is the coveralls thing. Please point me on some blog or tutorials how should I interpret and fix this thing (I'm aware of the abstract concept of "test coverage" but not the specifics of the message "Branches" and "Missed" 🤔

captura de pantalla 2018-05-12 a la s 16 02 14

**Comment by philippefutureboy** [comment]
Thanks for the great work! You are really helping making this library better  🎉 

* Did you solve the coveralls branch problem?
* Also, there are two linux-based tests that are failing on Windows (see AppVeyor)

Cheers ✨

**Comment by jacargentina** [comment]
I've found that using `os.EOL` and/or `splitEOL` was confusing.
The rule of thumb I've applied during refactoring is simply:

- No more replace `\ r\n` with `\n` by magic on testing windows
- Tests and sources for a given platform must know the specific platform EOL (NOT by `os.EOL`)

**Comment by jacargentina** [comment]
@philippefutureboy i think coverage decreased for the new `inferDevSize` thing. But i'm suspecting that code is not needed any more: i suspect previosuly (pre 2.0.0) size was `null` because of parsing errors. But now they are fixed, infer the size is not needed?

**Pull request merged**
